/* CHAR FUNCTION
    UPPER LOWER INITCAP
*/
-- 대문자 소문자 앞글자만 대문자
SELECT ENAME,UPPER(ENAME),LOWER(ENAME),INITCAP(ENAME)
FROM EMP;

SELECT * FROM EMP WHERE LOWER(ENAME)='james';

SELECT ENAME, LENGTH(ENAME), SAL, LENGTH(SAL), LENGTH('한글'),LENGTHB('한글')
FROM EMP;
 
--SUBSTR(JOB,1,2) 첫번째글자부터 두개 SUBSTR(JOB,5) 5번째부터 다
SELECT JOB, SUBSTR(JOB,1,2),SUBSTR(JOB,3,2),SUBSTR(JOB,5) 
            ,SUBSTR(JOB,-LENGTH(JOB)),SUBSTR(JOB, -LENGTH(JOB),2),SUBSTR(JOB,-3)
            FROM EMP;

SELECT INSTR('HELLO, ORACLE','L') INS1
            , INSTR('HELLO, ORACLE','L',5) INS2
            --INSTR 안에 문장에서 'L'이 몇번째에 있는지 찾겠다. 5번째 이후로 2번째 L을
            , INSTR('HELLO, ORACLE','L',2,2) INS3
FROM DUAL;

SELECT JOB, INSTR(JOB,'A',1,2)
FROM EMP
WHERE JOB LIKE '%A%';